[package]
name = "plunger"
version = "0.1.0-rc.0"
edition = "2024"

[features]
default = []
tokio = ["dep:tokio"]

[dependencies]
pinned-aliasable = "0.1"
pin-project-lite = "0.2"

tokio = { version = "1", optional = true, features = ["rt", "rt-multi-thread"] }
pollster = "0.4"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
